(() => {
  // Current voyage content remains in index.html. This script only restores
  // stable layout/behaviour and the voyage archive; it never rewrites day data.

  if (!document.getElementById('day17-layout-fixes')) {
    const style = document.createElement('style'); style.id='day17-layout-fixes'; style.textContent=`.ship-roll > .wrap{border:0;padding:0;box-shadow:none}#myth-day-17{padding-top:92px;padding-bottom:92px}#night-watch-day-17{padding-top:96px}@media(max-width:800px){.ship-roll > .wrap{padding:0}#myth-day-17{padding-top:82px}#night-watch-day-17{padding-top:86px}}`; document.head.appendChild(style);
  }
  const roll=document.querySelector('.ship-roll .roll-grid'); if(roll&&!document.querySelector('.captain-roll')){const captain=document.createElement('article');captain.className='captain-roll';captain.innerHTML='<span class="captain-label">THE CAPTAIN</span><span>Stefan</span><strong>HÁKON</strong><small class="old-norse">Hákon</small><small class="runes">ᚼᛅᚴᚢᚾ</small>';roll.parentNode.insertBefore(captain,roll);}
  const ourSaga=document.getElementById('our-saga-day-17');if(ourSaga&&!ourSaga.querySelector('img[src="day-17-our-saga.jpg"]')){const copy=ourSaga.querySelector('.copy');if(copy){const figure=document.createElement('figure');figure.className='framed';figure.innerHTML='<img class="zoomable" src="day-17-our-saga.jpg" alt="Our Saga — Day 17" loading="lazy"><figcaption>OUR SAGA — DAY 17</figcaption>';copy.appendChild(figure);}}
  const honors=document.getElementById('honors');if(honors){const figure=honors.querySelector('figure'),naming=honors.querySelector('.naming-list');if(figure&&naming){figure.classList.add('light');naming.parentNode.insertBefore(figure,naming);}}

  // Keeper's Chamber — moderated crew contributions plus the public Crew Voices record.
  const sagaAnchor=document.getElementById('our-saga-day-19')||document.getElementById('our-saga-day-17');
  if(sagaAnchor&&!document.getElementById('keepers-chamber')){
    const chamberStyle=document.createElement('style');chamberStyle.id='keepers-chamber-style';chamberStyle.textContent=`#keepers-chamber{padding:92px 0;background:#071116;border-top:1px solid rgba(201,163,91,.22);border-bottom:1px solid rgba(201,163,91,.22);scroll-behavior:smooth}#keepers-chamber .keeper-intro{max-width:760px;margin:0 0 1.1rem;color:#d9d1c2;line-height:1.75}.keeper-jump{display:inline-block;margin:0 0 1.6rem;padding:.72rem 1rem;border:1px solid rgba(201,163,91,.55);color:#c9a35b;text-decoration:none;font-size:.78rem;font-weight:800;letter-spacing:.12em}.keeper-jump:hover,.keeper-jump:focus{background:rgba(201,163,91,.08);color:#f1eadb}.keeper-jump:focus-visible{outline:2px solid #c9a35b;outline-offset:3px}#keepers-chamber .keeper-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.5rem}#keepers-chamber .keeper-card{min-width:0;padding:1.25rem;background:linear-gradient(145deg,rgba(114,18,27,.14),rgba(7,17,22,.95));border:1px solid rgba(201,163,91,.38)}#keepers-chamber .keeper-card span{display:block;color:#c9a35b;font-size:.75rem;font-weight:700;letter-spacing:.14em;margin-bottom:.65rem}#keepers-chamber .keeper-card strong{display:block;color:#f1eadb;font-size:1.05rem;margin-bottom:.6rem}#keepers-chamber .keeper-card p{margin:0;color:#cfc6b6;line-height:1.6}#keepers-chamber .keeper-card .keeper-card-note{margin-top:.85rem;color:#f1eadb;font-weight:700}#keepers-chamber .keeper-card .keeper-jump{margin:1.15rem 0 0}#keepers-chamber .keeper-quote{margin:2rem 0 0;padding:1.15rem 1.25rem;border-left:3px solid #c9a35b;background:rgba(201,163,91,.06);color:#f1eadb;font-style:italic}#keepers-chamber .keeper-note{margin-top:1.15rem;color:#9f9688;font-size:.86rem;line-height:1.55}@media(max-width:800px){#keepers-chamber{padding:76px 0}#keepers-chamber .keeper-grid{grid-template-columns:1fr}.keeper-jump{width:100%;text-align:center}#keepers-chamber .keeper-card .keeper-jump{margin-bottom:0}}`;document.head.appendChild(chamberStyle);
    const chamber=document.createElement('section');chamber.id='keepers-chamber';chamber.innerHTML=`<div class="wrap"><div class="kicker gold">🐦‍⬛ THE KEEPER'S CHAMBER</div><h2>EVERY VIKING CARRIES A STORY</h2><p class="keeper-intro">Some stories are written in steps. Some are told around the fire. Some are remembered long after the ships have sailed. Here, Þóra — Keeper of the Saga — gathers the voices of our crew so the voyage can be remembered by more than one storyteller.</p><div class="keeper-grid"><article class="keeper-card"><span>CREW VOICES</span><strong>Every voyage is carried not only by oars, but by voices.</strong><p>Here, the words of our crew are gathered and guarded by Þóra, Keeper of the Saga. Read the voices already carried into the chamber — or leave your own message for the Keeper.</p><p class="keeper-card-note">Nothing enters the saga until it has passed through the Keeper's hands.</p><a class="keeper-jump" href="crew-voices.html" aria-label="Open Crew Voices">ENTER CREW VOICES →</a></article><article class="keeper-card"><span>TALES FROM THE CREW</span><strong>Your Viking. Your voice.</strong><p>Longer stories can explore the people behind the oars and the paths that brought them aboard our fleet.</p></article><article class="keeper-card"><span>QUESTIONS & IDEAS</span><strong>Help shape what comes next</strong><p>The crew may ask questions, suggest ideas and help the Captain and Keeper discover where the saga wants to go.</p></article></div><div class="keeper-quote">“OUR SAGA IS THE CREW'S SAGA.”</div><p class="keeper-note">The Keeper's Chamber is curated rather than automatically published. Crew contributions remain theirs, and only public Viking identities are used on this site. Private real-world names are never displayed.</p></div>`;sagaAnchor.insertAdjacentElement('afterend',chamber);
  }
  // Keep the voyage seal inside the Ship's Log on mobile.
  setTimeout(()=>{const seal=document.querySelector('#voyage .seal'),head=document.querySelector('#voyage .status-head');if(!seal||!head||!window.matchMedia('(max-width: 800px)').matches)return;head.style.display='grid';head.style.gridTemplateColumns='minmax(0,1fr) 96px';head.style.columnGap='12px';head.style.alignItems='start';head.style.position='relative';seal.style.position='static';seal.style.width='96px';seal.style.maxWidth='96px';seal.style.height='auto';seal.style.right='';seal.style.top='';seal.style.margin='0';seal.style.transform='none';seal.style.justifySelf='end';seal.style.alignSelf='start';seal.style.zIndex='auto';},0);
  const box=document.getElementById('lightbox');if(!box)return;const full=box.querySelector('img'),close=box.querySelector('button');const shut=()=>{box.classList.remove('open');box.setAttribute('aria-hidden','true');if(full)full.removeAttribute('src');document.body.classList.remove('lightbox-open')};const openImage=img=>{if(!full||!img)return;full.src=img.src;full.alt=img.alt||'Enlarged voyage artwork';box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.classList.add('lightbox-open')};document.querySelectorAll('img.zoomable,.framed img,.gallery-grid img,.archive-day img').forEach(img=>img.addEventListener('click',event=>{if(img.closest('a.archive-day'))return;event.preventDefault();openImage(img)}));if(close)close.addEventListener('click',shut);box.addEventListener('click',event=>{if(event.target===box)shut()});document.addEventListener('keydown',event=>{if(event.key==='Escape')shut()});
})();
