(() => {
  // Current voyage content remains in index.html. This script only restores
  // stable layout/behaviour and the voyage archive; it never rewrites day data.

  if (!document.getElementById('day17-layout-fixes')) {
    const style = document.createElement('style'); style.id='day17-layout-fixes'; style.textContent=`.ship-roll > .wrap{border:0;padding:0;box-shadow:none}#myth-day-17{padding-top:92px;padding-bottom:92px}#night-watch-day-17{padding-top:96px}@media(max-width:800px){.ship-roll > .wrap{padding:0}#myth-day-17{padding-top:82px}#night-watch-day-17{padding-top:86px}}`; document.head.appendChild(style);
  }
  const roll=document.querySelector('.ship-roll .roll-grid'); if(roll&&!document.querySelector('.captain-roll')){const captain=document.createElement('article');captain.className='captain-roll';captain.innerHTML='<span class="captain-label">THE CAPTAIN</span><span>Stefan</span><strong>HÁKON</strong><small class="old-norse">Hákon</small><small class="runes">ᚼᛅᚴᚢᚾ</small>';roll.parentNode.insertBefore(captain,roll);}
  const ourSaga=document.getElementById('our-saga-day-17');if(ourSaga&&!ourSaga.querySelector('img[src="day-17-our-saga.jpg"]')){const copy=ourSaga.querySelector('.copy');if(copy){const figure=document.createElement('figure');figure.className='framed';figure.innerHTML='<img class="zoomable" src="day-17-our-saga.jpg" alt="Our Saga — Day 17" loading="lazy"><figcaption>OUR SAGA — DAY 17</figcaption>';copy.appendChild(figure);}}
  const honors=document.getElementById('honors');if(honors){const figure=honors.querySelector('figure'),naming=honors.querySelector('.naming-list');if(figure&&naming){figure.classList.add('light');naming.parentNode.insertBefore(figure,naming);}}

  // Keeper's Chamber — moderated crew contributions plus the public Crew Voices record.
  const sagaAnchor=document.getElementById('our-saga-day-19')||document.getElementById('our-saga-day-17');
  if(sagaAnchor&&!document.getElementById('keepers-chamber')){
    const chamberStyle=document.createElement('style');chamberStyle.id='keepers-chamber-style';chamberStyle.textContent=`#keepers-chamber{padding:92px 0;background:#071116;border-top:1px solid rgba(201,163,91,.22);border-bottom:1px solid rgba(201,163,91,.22)}#keepers-chamber .keeper-intro{max-width:760px;margin:0 0 1.8rem;color:#d9d1c2;line-height:1.75}#keepers-chamber .keeper-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.5rem}#keepers-chamber .keeper-card{min-width:0;padding:1.25rem;background:linear-gradient(145deg,rgba(114,18,27,.14),rgba(7,17,22,.95));border:1px solid rgba(201,163,91,.38)}#keepers-chamber .keeper-card span{display:block;color:#c9a35b;font-size:.75rem;font-weight:700;letter-spacing:.14em;margin-bottom:.65rem}#keepers-chamber .keeper-card strong{display:block;color:#f1eadb;font-size:1.05rem;margin-bottom:.6rem}#keepers-chamber .keeper-card p{margin:0;color:#cfc6b6;line-height:1.6}#keepers-chamber .keeper-quote{margin:2rem 0 0;padding:1.15rem 1.25rem;border-left:3px solid #c9a35b;background:rgba(201,163,91,.06);color:#f1eadb;font-style:italic}#keepers-chamber .keeper-note{margin-top:1.15rem;color:#9f9688;font-size:.86rem;line-height:1.55}.crew-voices-public{margin-top:3rem;padding-top:2.3rem;border-top:1px solid rgba(201,163,91,.3)}.crew-voices-public h3{font-family:Georgia,serif;color:#f1eadb;font-size:clamp(1.8rem,5vw,2.8rem);margin:.35rem 0}.crew-voices-public .cv-intro{color:#b8ae9e;line-height:1.65;max-width:720px}.cv-list{display:grid;gap:1rem;margin-top:1.4rem}.cv-entry{padding:1.2rem;border:1px solid rgba(201,163,91,.35);background:rgba(9,23,28,.7)}.cv-name{font-family:Georgia,serif;color:#c9a35b;font-size:1.2rem}.cv-message{white-space:pre-wrap;line-height:1.65;margin:.65rem 0}.cv-date{color:#9f9688;font-size:.78rem;letter-spacing:.08em}.cv-empty{padding:1.15rem;border:1px solid rgba(201,163,91,.3);color:#b8ae9e}@media(max-width:800px){#keepers-chamber{padding:76px 0}#keepers-chamber .keeper-grid{grid-template-columns:1fr}}`;document.head.appendChild(chamberStyle);
    const chamber=document.createElement('section');chamber.id='keepers-chamber';chamber.innerHTML=`<div class="wrap"><div class="kicker gold">🐦‍⬛ THE KEEPER'S CHAMBER</div><h2>EVERY VIKING CARRIES A STORY</h2><p class="keeper-intro">Some stories are written in steps. Some are told around the fire. Some are remembered long after the ships have sailed. Here, Þóra — Keeper of the Saga — gathers the voices of our crew so the voyage can be remembered by more than one storyteller.</p><div class="keeper-grid"><article class="keeper-card"><span>CREW VOICES</span><strong>Leave your mark on the saga</strong><p>Short thoughts, memories, reactions and moments from the voyage can become part of the crew's living record.</p></article><article class="keeper-card"><span>TALES FROM THE CREW</span><strong>Your Viking. Your voice.</strong><p>Longer stories can explore the people behind the oars and the paths that brought them aboard our fleet.</p></article><article class="keeper-card"><span>QUESTIONS & IDEAS</span><strong>Help shape what comes next</strong><p>The crew may ask questions, suggest ideas and help the Captain and Keeper discover where the saga wants to go.</p></article></div><div class="keeper-quote">“OUR SAGA IS THE CREW'S SAGA.”</div><p class="keeper-note">The Keeper's Chamber is curated rather than automatically published. Crew contributions remain theirs, and only public Viking identities are used on this site. Private real-world names are never displayed.</p><section class="crew-voices-public" id="crew-voices"><div class="kicker gold">CREW VOICES</div><h3>VOICES FROM THE SHIP</h3><p class="cv-intro">Words carried from the crew and chosen by the Keepers to enter our shared voyage.</p><div class="cv-list" id="crew-voices-list"><div class="cv-empty">Listening for voices from the ship…</div></div></section></div>`;sagaAnchor.insertAdjacentElement('afterend',chamber);
  }
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cvList=document.getElementById('crew-voices-list');if(cvList){fetch('/api/crew-voices-public',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok||!d.ok)throw Error();cvList.innerHTML=d.voices.length?d.voices.map(x=>`<article class="cv-entry"><div class="cv-name">${esc(x.identity)}</div><div class="cv-message">${esc(x.message)}</div><div class="cv-date">${esc(new Date(x.publishedAt||x.submittedAt).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'}))}</div></article>`).join(''):'<div class="cv-empty">No Crew Voices have been published yet.</div>';}).catch(()=>cvList.innerHTML='<div class="cv-empty">The voices cannot be reached right now.</div>');}
  if(document.getElementById('keepers-chamber')&&!document.getElementById('keepers-chamber-form-loader')){const s=document.createElement('script');s.id='keepers-chamber-form-loader';s.src='keepers-chamber.js?v=preview-2';document.body.appendChild(s);}

  // Keep the voyage seal inside the Ship's Log on mobile.
  setTimeout(()=>{const seal=document.querySelector('#voyage .seal'),head=document.querySelector('#voyage .status-head');if(!seal||!head||!window.matchMedia('(max-width: 800px)').matches)return;head.style.display='grid';head.style.gridTemplateColumns='minmax(0,1fr) 96px';head.style.columnGap='12px';head.style.alignItems='start';head.style.position='relative';seal.style.position='static';seal.style.width='96px';seal.style.maxWidth='96px';seal.style.height='auto';seal.style.right='';seal.style.top='';seal.style.margin='0';seal.style.transform='none';seal.style.justifySelf='end';seal.style.alignSelf='start';seal.style.zIndex='auto';},0);
  const box=document.getElementById('lightbox');if(!box)return;const full=box.querySelector('img'),close=box.querySelector('button');const shut=()=>{box.classList.remove('open');box.setAttribute('aria-hidden','true');if(full)full.removeAttribute('src');document.body.classList.remove('lightbox-open')};const openImage=img=>{if(!full||!img)return;full.src=img.src;full.alt=img.alt||'Enlarged voyage artwork';box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.classList.add('lightbox-open')};document.querySelectorAll('img.zoomable,.framed img,.gallery-grid img,.archive-day img').forEach(img=>img.addEventListener('click',event=>{if(img.closest('a.archive-day'))return;event.preventDefault();openImage(img)}));if(close)close.addEventListener('click',shut);box.addEventListener('click',event=>{if(event.target===box)shut()});document.addEventListener('keydown',event=>{if(event.key==='Escape')shut()});
})();
