import crypto from 'node:crypto';
import { get, list, put, del } from '@vercel/blob';
const json=(res,status,payload)=>{res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(payload));};
const safeEqual=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y);};
const isKeeper=req=>{const secret=process.env.KEEPER_ADMIN_SECRET||'';if(!secret)return false;const raw=String(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('keeper_session='));if(!raw)return false;const value=decodeURIComponent(raw.slice('keeper_session='.length));const [expires,signature]=value.split('.');if(!expires||!signature||Number(expires)<Math.floor(Date.now()/1000))return false;const expected=crypto.createHmac('sha256',secret).update(expires).digest('hex');return safeEqual(signature,expected);};
const sameOrigin=req=>{const origin=String(req.headers.origin||''),host=String(req.headers['x-forwarded-host']||req.headers.host||'');if(!origin||!host)return false;try{return new URL(origin).host===host}catch{return false}};
const allowed=(value,bucket)=>{const p=String(value||'');return p.startsWith(`keepers-chamber/${bucket}/`)&&p.endsWith('.json')?p:null;};
const read=async pathname=>{const r=await get(pathname,{access:'private',useCache:false});if(!r?.stream)return null;return JSON.parse(await new Response(r.stream).text());};
const readBucket=async status=>{const result=await list({prefix:`keepers-chamber/${status}/`});const blobs=[...(result.blobs||[])].sort((a,b)=>new Date(b.uploadedAt||0)-new Date(a.uploadedAt||0)).slice(0,50),messages=[];for(const blob of blobs){const x=await read(blob.pathname);if(x?.kind!=='crew-voice')continue;messages.push({id:blob.pathname,identity:x.identity,message:x.message,submittedAt:x.submittedAt,status:x.status,decidedAt:x.moderation?.decidedAt||null,publishedAt:x.publication?.publishedAt||null,automaticPublishing:x.privacy?.automaticPublishing===true});}return messages;};
const move=async(from,to,payload)=>{const filename=from.split('/').pop();await put(`keepers-chamber/${to}/${filename}`,JSON.stringify(payload,null,2),{access:'private',addRandomSuffix:false,allowOverwrite:false,contentType:'application/json'});await del(from);};
export default async function handler(req,res){
 if(process.env.VERCEL_ENV!=='preview')return json(res,404,{ok:false,error:'Not found.'});
 if(!isKeeper(req))return json(res,401,{ok:false,error:'Keeper authentication required.'});
 if(req.method==='GET'){try{const [pending,approved,rejected,published]=await Promise.all(['pending','approved','rejected','published'].map(readBucket));return json(res,200,{ok:true,counts:{pending:pending.length,approved:approved.length,rejected:rejected.length,published:published.length},pending,approved,rejected,published});}catch(error){console.error('Keeper inbox read failed:',error);return json(res,500,{ok:false,error:'The Keeper could not open the message chest.'});}}
 if(req.method==='POST'){
  if(!sameOrigin(req))return json(res,403,{ok:false,error:'Invalid request origin.'});
  try{const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),action=body.action;
   if(action==='approve'||action==='reject'){const pathname=allowed(body.id,'pending'),to=action==='approve'?'approved':'rejected';if(!pathname)return json(res,400,{ok:false,error:'Invalid moderation request.'});const stored=await read(pathname);if(!stored||stored.kind!=='crew-voice'||stored.status!=='pending')return json(res,409,{ok:false,error:'This Crew Voice is no longer pending.'});const moderated={...stored,status:to,moderation:{decision:action,decidedAt:new Date().toISOString(),automaticPublishing:false},privacy:{...(stored.privacy||{}),automaticPublishing:false}};await move(pathname,to,moderated);return json(res,200,{ok:true,status:to,automaticPublishing:false,message:action==='approve'?'Crew Voice approved. It has NOT been published.':'Crew Voice rejected and archived.'});}
   if(action==='publish'){const pathname=allowed(body.id,'approved');if(!pathname)return json(res,400,{ok:false,error:'Invalid publication request.'});const stored=await read(pathname);if(!stored||stored.kind!=='crew-voice'||stored.status!=='approved')return json(res,409,{ok:false,error:'This Crew Voice is no longer approved.'});const published={...stored,status:'published',publication:{publishedAt:new Date().toISOString()},privacy:{...(stored.privacy||{}),automaticPublishing:false}};await move(pathname,'published',published);return json(res,200,{ok:true,status:'published',message:'Crew Voice published to Crew Voices.'});}
   if(action==='unpublish'){const pathname=allowed(body.id,'published');if(!pathname)return json(res,400,{ok:false,error:'Invalid unpublish request.'});const stored=await read(pathname);if(!stored||stored.kind!=='crew-voice'||stored.status!=='published')return json(res,409,{ok:false,error:'This Crew Voice is no longer published.'});const approved={...stored,status:'approved',publication:{...(stored.publication||{}),unpublishedAt:new Date().toISOString()},privacy:{...(stored.privacy||{}),automaticPublishing:false}};await move(pathname,'approved',approved);return json(res,200,{ok:true,status:'approved',message:'Crew Voice unpublished and returned to Approved.'});}
   return json(res,400,{ok:false,error:'Invalid moderation request.'});
  }catch(error){console.error('Keeper action failed:',error);return json(res,500,{ok:false,error:'The Keeper could not complete that action.'});}
 }
 res.setHeader('Allow','GET, POST');return json(res,405,{ok:false,error:'Method not allowed.'});
}
